---
openapi: 3.0.1
info:
  title: Good Night App API
  version: v1
paths:
  "/api/v1/user/{user_id}/follow":
    post:
      tags:
      - User
      summary: Follow a user
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                followed_id:
                  type: integer
              required:
              - followed_id
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/user/{user_id}/unfollow":
    delete:
      tags:
      - User
      summary: Unfollow a user
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: followed_id
        in: query
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/user/{user_id}/following":
    get:
      tags:
      - User
      summary: Get user that the given user is following
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        description: Page number (1-based)
        required: false
        schema:
          type: integer
          default: 1
      - name: per_page
        in: query
        description: Items per page
        required: false
        schema:
          type: integer
          default: 25
      responses:
        '200':
          description: List of user the user is following
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      next_page:
                        type: integer
                      prev_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/user/{user_id}/followers":
    get:
      tags:
      - User
      summary: Get user who follow the given user
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        description: Page number (1-based)
        required: false
        schema:
          type: integer
          default: 1
      - name: per_page
        in: query
        description: Items per page
        required: false
        schema:
          type: integer
          default: 25
      responses:
        '200':
          description: List of followers
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        name:
                          type: string
                  pagination:
                    type: object
                    properties:
                      current_page:
                        type: integer
                      next_page:
                        type: integer
                      prev_page:
                        type: integer
                      total_pages:
                        type: integer
                      total_count:
                        type: integer
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/session/{user_id}/sleep":
    post:
      tags:
      - Session
      summary: Start a sleep session for the user
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  session:
                    type: object
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/session/{user_id}/wake":
    post:
      tags:
      - Session
      summary: End the current sleep session
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  session:
                    type: object
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/session/{user_id}/history":
    get:
      tags:
      - Session
      summary: Get sleep history (paginated)
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        schema:
          type: integer
      - name: per_page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                  pagination:
                    type: object
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  "/api/v1/session/{user_id}/friends_weekly":
    get:
      tags:
      - Session
      summary: Get friends weekly sessions (paginated)
      parameters:
      - name: user_id
        in: path
        required: true
        schema:
          type: integer
      - name: page
        in: query
        schema:
          type: integer
      - name: per_page
        in: query
        schema:
          type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                  pagination:
                    type: object
        '404':
          description: Not Found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
components: {}
