pgsql: &pgsql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV['DB_POOL'] || 5 %>
  checkout_timeout: <%= ENV['DB_TIMEOUT'] || 5000 %>

defaults: &defaults
  gssencmode: disable
  <<: *<%= ENV['DB'] || "pgsql" %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

test:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

development:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

staging:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>

production:
  <<: *defaults
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  database: <%= ENV['DB_NAME'] %>
  port: <%= ENV['DB_PORT'] || 5432 %>