pgsql: &pgsql
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('DB_POOL', 5) %>
  checkout_timeout: <%= ENV.fetch('DB_TIMEOUT', 5000) %>

defaults: &defaults
  gssencmode: disable
  <<: *pgsql
  host: <%= ENV.fetch('DB_HOST', 'localhost') %>
  username: <%= ENV.fetch('DB_USER', 'postgres') %>
  password: <%= ENV.fetch('DB_PASSWORD', '') %>
  port: <%= ENV.fetch('DB_PORT', 5432) %>

# Per-environment configurations. If DATABASE_URL is provided, Rails will use that
# automatically, otherwise these values will be used.

test:
  <<: *defaults
  database: <%= ENV.fetch('DB_NAME', "good_night_app_test") %>

development:
  <<: *defaults
  database: <%= ENV.fetch('DB_NAME', "good_night_app_development") %>

staging:
  <<: *defaults
  database: <%= ENV.fetch('DB_NAME', "good_night_app_staging") %>

production:
  <<: *defaults
  database: <%= ENV.fetch('DB_NAME', "good_night_app_production") %>